### ISSUE TITLE
empty string error and matplotlib missing

### ISSUE THREAD

**Issue by edwo314** [zephyris/tryptag#21]
When calling gene_list a second time in tryptag.py or any function like open_cell that calls gene_list, I am getting a list index out of range in line 350
`if line[indices[p + "status"]] == "cell line generated":` . This happens because the line variable is sometimes an empty string.
An easy fix for that problem is changing line 333 to `lines = [line for line in self._fetch_zenodo_record_file(zenodo_json, "localisations.tsv").splitlines() if line.strip()]`, as it discards empty lines. This change doesn't alter the program's intended behaviour.

The second issue I noticed is that tryptools.py is using matplotlib, but matplotlib is not being installed automatically.
This can be fixed by adding matplotlib to the dependencies list in the pyproject.toml file.

I didn't want to fork the project as those are only minor bugs and you might want to verify them first.

**Comment by zephyris** [comment]
Thanks for reporting these. I'll definitely add `matplotlib`. I'd want to double-check the line strip, but is probably discarding only trailing lines and is safe...
